print("I am gonna ask you a few questions, hope you don't mind?")
username = input("What is your name: ")
favoriteFood = input("What's your favorite food: ")
favoriteMusic = input("what's your favorite music: ")
location = input("Where do you live: ")
print()
print("Getting to know you!")
print("You are")
print(username)
print("You're probably hungry for")
print(favoriteFood)
print("and you're definitely getting your groove on to")
print(favoriteMusic)
print("living in the amazing")
print(location)

